# Forces new Travis-CI Infrastructure
sudo: false

language: php

env:
  global:
    - COMPOSER_FLAGS="--prefer-stable"
    - PHPUNIT_FLAGS=""
    - USE_SCRUTINIZER="no"

matrix:
  include:
    - php: 7.2
      env: COMPOSER_FLAGS="--prefer-stable --prefer-lowest"
    - php: 7.2
      env: PHPUNIT_FLAGS="--coverage-clover=coverage.clover" USE_SCRUTINIZER="yes"
    - php: 7.3
    - php: 7.3
      # This empty flag removes the prefer-stable switch to cause dev dependencies to be installed
      env: COMPOSER_FLAGS=""
    - php: 7.4snapshot
    - php: nightly
  allow_failures:
    - php: nightly

before_install:
  - travis_retry composer self-update

install:
  - travis_retry composer update $COMPOSER_FLAGS

script:
  - vendor/bin/phpunit $PHPUNIT_FLAGS
  - if [ "$USE_SCRUTINIZER" == "yes" ]; then wget https://scrutinizer-ci.com/ocular.phar; fi;
  - if [ "$USE_SCRUTINIZER" == "yes" ]; then php ocular.phar code-coverage:upload --format=php-clover coverage.clover; fi;

jobs:
  include:
    - stage: test
      name: PHPSTAN
      script: composer phpstan
    -
      name: CS
      script: composer cs
